# Generated by Django 2.1.2 on 2018-10-23 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='reported_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
