# Generated by Django 2.1.2 on 2018-10-23 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0002_auto_20181023_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='reported_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
