# Generated by Django 2.1.2 on 2019-01-24 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0005_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='location',
            field=models.TextField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
