# Generated by Django 2.1.2 on 2019-01-26 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0006_victim_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rescue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ussd.Victim')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ussd.Volunteer')),
            ],
        ),
    ]
