# Generated by Django 2.1.2 on 2019-01-26 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0007_rescue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rescue',
            name='victim',
        ),
        migrations.RemoveField(
            model_name='rescue',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='victim',
            name='volunteer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ussd.Volunteer'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Rescue',
        ),
    ]
