# Generated by Django 2.1.2 on 2018-10-26 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=80)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
